name: Groq Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  review:

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Packages
        run: |
          pip install groq

      - name: Fetch Main Branch
        run: |
          git fetch origin main:main

      - name: Run Review
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python Myproject_folder/review_code.py

      - name: Add Comment To PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('review.txt', 'utf8');

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: review
            });